algorithm: a2c
env_id: Hopper-v5
seed: 4
total_timesteps: 1000000
policy: MlpPolicy
verbose: 0
checkpoint_freq: 0
eval_freq: 0
algo_params:
  learning_rate: 0.001
  n_steps: 16
  gamma: 0.99
  gae_lambda: 0.95
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
