algorithm: td3
env_id: HalfCheetah-v5
seed: 0
total_timesteps: 1000000
policy: MlpPolicy
verbose: 0
checkpoint_freq: 0
eval_freq: 0
algo_params:
  learning_rate: 0.0003
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  policy_delay: 2
  target_policy_noise: 0.2
